import '../styles/globals.css';
import Head from 'next/head';
import Navbar from '../components/Navbar';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      {/* Components were overlapping with my navbar so had to add padding at the top, not 100% sure how to avoid */}
      <div className='pt-32'>
        <Component {...pageProps} />
      </div>
    </>
  );
}

export default MyApp;
